[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
Spaces = false
LongSentences = false

[language-server.tinymist]
command = "tinymist"

[language-server.mpls]
command = "mpls"
args = ["--enable-emoji"]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls", "mpls"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
indent = { tab-width = 2, unit = " " }

[[language]]
name = "javascript"
file-types = ["js"]
