[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
Spaces = false
LongSentences = false

[language-server.tinymist]
command = "tinymist"

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
indent = {tab-width = 2, unit = " "}
