[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
Spaces = false
LongSentences = false

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls"]
